package com.example.softwarearchitecture.model;

import java.util.Date;

public class Athletes {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column athletes.id
     *
     * @mbg.generated Wed Nov 11 22:13:40 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column athletes.name
     *
     * @mbg.generated Wed Nov 11 22:13:40 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column athletes.birthday
     *
     * @mbg.generated Wed Nov 11 22:13:40 CST 2020
     */
    private Date birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column athletes.gender
     *
     * @mbg.generated Wed Nov 11 22:13:40 CST 2020
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column athletes.height
     *
     * @mbg.generated Wed Nov 11 22:13:40 CST 2020
     */
    private Double height;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column athletes.weight
     *
     * @mbg.generated Wed Nov 11 22:13:40 CST 2020
     */
    private Double weight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column athletes.department
     *
     * @mbg.generated Wed Nov 11 22:13:40 CST 2020
     */
    private String department;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column athletes.body_condition
     *
     * @mbg.generated Wed Nov 11 22:13:40 CST 2020
     */
    private String bodyCondition;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column athletes.banned
     *
     * @mbg.generated Wed Nov 11 22:13:40 CST 2020
     */
    private Boolean banned;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column athletes.id
     *
     * @return the value of athletes.id
     *
     * @mbg.generated Wed Nov 11 22:13:40 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column athletes.id
     *
     * @param id the value for athletes.id
     *
     * @mbg.generated Wed Nov 11 22:13:40 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column athletes.name
     *
     * @return the value of athletes.name
     *
     * @mbg.generated Wed Nov 11 22:13:40 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column athletes.name
     *
     * @param name the value for athletes.name
     *
     * @mbg.generated Wed Nov 11 22:13:40 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column athletes.birthday
     *
     * @return the value of athletes.birthday
     *
     * @mbg.generated Wed Nov 11 22:13:40 CST 2020
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column athletes.birthday
     *
     * @param birthday the value for athletes.birthday
     *
     * @mbg.generated Wed Nov 11 22:13:40 CST 2020
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column athletes.gender
     *
     * @return the value of athletes.gender
     *
     * @mbg.generated Wed Nov 11 22:13:40 CST 2020
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column athletes.gender
     *
     * @param gender the value for athletes.gender
     *
     * @mbg.generated Wed Nov 11 22:13:40 CST 2020
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column athletes.height
     *
     * @return the value of athletes.height
     *
     * @mbg.generated Wed Nov 11 22:13:40 CST 2020
     */
    public Double getHeight() {
        return height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column athletes.height
     *
     * @param height the value for athletes.height
     *
     * @mbg.generated Wed Nov 11 22:13:40 CST 2020
     */
    public void setHeight(Double height) {
        this.height = height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column athletes.weight
     *
     * @return the value of athletes.weight
     *
     * @mbg.generated Wed Nov 11 22:13:40 CST 2020
     */
    public Double getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column athletes.weight
     *
     * @param weight the value for athletes.weight
     *
     * @mbg.generated Wed Nov 11 22:13:40 CST 2020
     */
    public void setWeight(Double weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column athletes.department
     *
     * @return the value of athletes.department
     *
     * @mbg.generated Wed Nov 11 22:13:40 CST 2020
     */
    public String getDepartment() {
        return department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column athletes.department
     *
     * @param department the value for athletes.department
     *
     * @mbg.generated Wed Nov 11 22:13:40 CST 2020
     */
    public void setDepartment(String department) {
        this.department = department == null ? null : department.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column athletes.body_condition
     *
     * @return the value of athletes.body_condition
     *
     * @mbg.generated Wed Nov 11 22:13:40 CST 2020
     */
    public String getBodyCondition() {
        return bodyCondition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column athletes.body_condition
     *
     * @param bodyCondition the value for athletes.body_condition
     *
     * @mbg.generated Wed Nov 11 22:13:40 CST 2020
     */
    public void setBodyCondition(String bodyCondition) {
        this.bodyCondition = bodyCondition == null ? null : bodyCondition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column athletes.banned
     *
     * @return the value of athletes.banned
     *
     * @mbg.generated Wed Nov 11 22:13:40 CST 2020
     */
    public Boolean getBanned() {
        return banned;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column athletes.banned
     *
     * @param banned the value for athletes.banned
     *
     * @mbg.generated Wed Nov 11 22:13:40 CST 2020
     */
    public void setBanned(Boolean banned) {
        this.banned = banned;
    }
}