package com.example.softwarearchitecture.model;

import java.util.Date;

public class Compitition {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column compitition.id
     *
     * @mbg.generated Wed Nov 11 22:13:40 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column compitition.name
     *
     * @mbg.generated Wed Nov 11 22:13:40 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column compitition.responsible_person
     *
     * @mbg.generated Wed Nov 11 22:13:40 CST 2020
     */
    private String responsiblePerson;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column compitition.rank
     *
     * @mbg.generated Wed Nov 11 22:13:40 CST 2020
     */
    private Integer rank;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column compitition.hold_time
     *
     * @mbg.generated Wed Nov 11 22:13:40 CST 2020
     */
    private Date holdTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column compitition.position
     *
     * @mbg.generated Wed Nov 11 22:13:40 CST 2020
     */
    private String position;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column compitition.compitition_rules
     *
     * @mbg.generated Wed Nov 11 22:13:40 CST 2020
     */
    private String compititionRules;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column compitition.id
     *
     * @return the value of compitition.id
     *
     * @mbg.generated Wed Nov 11 22:13:40 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column compitition.id
     *
     * @param id the value for compitition.id
     *
     * @mbg.generated Wed Nov 11 22:13:40 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column compitition.name
     *
     * @return the value of compitition.name
     *
     * @mbg.generated Wed Nov 11 22:13:40 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column compitition.name
     *
     * @param name the value for compitition.name
     *
     * @mbg.generated Wed Nov 11 22:13:40 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column compitition.responsible_person
     *
     * @return the value of compitition.responsible_person
     *
     * @mbg.generated Wed Nov 11 22:13:40 CST 2020
     */
    public String getResponsiblePerson() {
        return responsiblePerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column compitition.responsible_person
     *
     * @param responsiblePerson the value for compitition.responsible_person
     *
     * @mbg.generated Wed Nov 11 22:13:40 CST 2020
     */
    public void setResponsiblePerson(String responsiblePerson) {
        this.responsiblePerson = responsiblePerson == null ? null : responsiblePerson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column compitition.rank
     *
     * @return the value of compitition.rank
     *
     * @mbg.generated Wed Nov 11 22:13:40 CST 2020
     */
    public Integer getRank() {
        return rank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column compitition.rank
     *
     * @param rank the value for compitition.rank
     *
     * @mbg.generated Wed Nov 11 22:13:40 CST 2020
     */
    public void setRank(Integer rank) {
        this.rank = rank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column compitition.hold_time
     *
     * @return the value of compitition.hold_time
     *
     * @mbg.generated Wed Nov 11 22:13:40 CST 2020
     */
    public Date getHoldTime() {
        return holdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column compitition.hold_time
     *
     * @param holdTime the value for compitition.hold_time
     *
     * @mbg.generated Wed Nov 11 22:13:40 CST 2020
     */
    public void setHoldTime(Date holdTime) {
        this.holdTime = holdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column compitition.position
     *
     * @return the value of compitition.position
     *
     * @mbg.generated Wed Nov 11 22:13:40 CST 2020
     */
    public String getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column compitition.position
     *
     * @param position the value for compitition.position
     *
     * @mbg.generated Wed Nov 11 22:13:40 CST 2020
     */
    public void setPosition(String position) {
        this.position = position == null ? null : position.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column compitition.compitition_rules
     *
     * @return the value of compitition.compitition_rules
     *
     * @mbg.generated Wed Nov 11 22:13:40 CST 2020
     */
    public String getCompititionRules() {
        return compititionRules;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column compitition.compitition_rules
     *
     * @param compititionRules the value for compitition.compitition_rules
     *
     * @mbg.generated Wed Nov 11 22:13:40 CST 2020
     */
    public void setCompititionRules(String compititionRules) {
        this.compititionRules = compititionRules == null ? null : compititionRules.trim();
    }
}