package com.example.softwarearchitecture.model;

public class Referee {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column referee.id
     *
     * @mbg.generated Wed Nov 11 22:13:40 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column referee.name
     *
     * @mbg.generated Wed Nov 11 22:13:40 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column referee.birthday
     *
     * @mbg.generated Wed Nov 11 22:13:40 CST 2020
     */
    private String birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column referee.faculty
     *
     * @mbg.generated Wed Nov 11 22:13:40 CST 2020
     */
    private String faculty;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column referee.title
     *
     * @mbg.generated Wed Nov 11 22:13:40 CST 2020
     */
    private String title;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column referee.id
     *
     * @return the value of referee.id
     *
     * @mbg.generated Wed Nov 11 22:13:40 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column referee.id
     *
     * @param id the value for referee.id
     *
     * @mbg.generated Wed Nov 11 22:13:40 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column referee.name
     *
     * @return the value of referee.name
     *
     * @mbg.generated Wed Nov 11 22:13:40 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column referee.name
     *
     * @param name the value for referee.name
     *
     * @mbg.generated Wed Nov 11 22:13:40 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column referee.birthday
     *
     * @return the value of referee.birthday
     *
     * @mbg.generated Wed Nov 11 22:13:40 CST 2020
     */
    public String getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column referee.birthday
     *
     * @param birthday the value for referee.birthday
     *
     * @mbg.generated Wed Nov 11 22:13:40 CST 2020
     */
    public void setBirthday(String birthday) {
        this.birthday = birthday == null ? null : birthday.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column referee.faculty
     *
     * @return the value of referee.faculty
     *
     * @mbg.generated Wed Nov 11 22:13:40 CST 2020
     */
    public String getFaculty() {
        return faculty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column referee.faculty
     *
     * @param faculty the value for referee.faculty
     *
     * @mbg.generated Wed Nov 11 22:13:40 CST 2020
     */
    public void setFaculty(String faculty) {
        this.faculty = faculty == null ? null : faculty.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column referee.title
     *
     * @return the value of referee.title
     *
     * @mbg.generated Wed Nov 11 22:13:40 CST 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column referee.title
     *
     * @param title the value for referee.title
     *
     * @mbg.generated Wed Nov 11 22:13:40 CST 2020
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }
}