package com.example.softwarearchitecture.vo;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.util.Date;

@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
public class AthletesVO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column athletes.id
     *
     * @mbg.generated Wed Nov 11 22:13:40 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column athletes.name
     *
     * @mbg.generated Wed Nov 11 22:13:40 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column athletes.birthday
     *
     * @mbg.generated Wed Nov 11 22:13:40 CST 2020
     */
    private Date birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column athletes.gender
     *
     * @mbg.generated Wed Nov 11 22:13:40 CST 2020
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column athletes.height
     *
     * @mbg.generated Wed Nov 11 22:13:40 CST 2020
     */
    private Double height;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column athletes.weight
     *
     * @mbg.generated Wed Nov 11 22:13:40 CST 2020
     */
    private Double weight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column athletes.department
     *
     * @mbg.generated Wed Nov 11 22:13:40 CST 2020
     */
    private String department;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column athletes.body_condition
     *
     * @mbg.generated Wed Nov 11 22:13:40 CST 2020
     */
    private String bodyCondition;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column athletes.banned
     *
     * @mbg.generated Wed Nov 11 22:13:40 CST 2020
     */
    private Boolean banned;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column athletes.id
     *
     * @return the value of athletes.id
     *
     * @mbg.generated Wed Nov 11 22:13:40 CST 2020
     */
    private Integer code;
}
