package com.example.softwarearchitecture.dao;

import com.example.softwarearchitecture.model.Athletes;
import com.example.softwarearchitecture.model.AthletesExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Mapper
public interface AthletesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table athletes
     *
     * @mbg.generated Wed Nov 11 22:13:40 CST 2020
     */
    int deleteByExample(AthletesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table athletes
     *
     * @mbg.generated Wed Nov 11 22:13:40 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table athletes
     *
     * @mbg.generated Wed Nov 11 22:13:40 CST 2020
     */
    int insert(Athletes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table athletes
     *
     * @mbg.generated Wed Nov 11 22:13:40 CST 2020
     */
    int insertSelective(Athletes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table athletes
     *
     * @mbg.generated Wed Nov 11 22:13:40 CST 2020
     */
    List<Athletes> selectByExample(AthletesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table athletes
     *
     * @mbg.generated Wed Nov 11 22:13:40 CST 2020
     */
    Athletes selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table athletes
     *
     * @mbg.generated Wed Nov 11 22:13:40 CST 2020
     */
    int updateByExampleSelective(@Param("record") Athletes record, @Param("example") AthletesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table athletes
     *
     * @mbg.generated Wed Nov 11 22:13:40 CST 2020
     */
    int updateByExample(@Param("record") Athletes record, @Param("example") AthletesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table athletes
     *
     * @mbg.generated Wed Nov 11 22:13:40 CST 2020
     */
    int updateByPrimaryKeySelective(Athletes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table athletes
     *
     * @mbg.generated Wed Nov 11 22:13:40 CST 2020
     */
    int updateByPrimaryKey(Athletes record);
}