package com.example.softwarearchitecture.dao;

import com.example.softwarearchitecture.model.Compitition;
import com.example.softwarearchitecture.model.CompititionExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface CompititionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table compitition
     *
     * @mbg.generated Wed Nov 11 22:13:40 CST 2020
     */
    int deleteByExample(CompititionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table compitition
     *
     * @mbg.generated Wed Nov 11 22:13:40 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table compitition
     *
     * @mbg.generated Wed Nov 11 22:13:40 CST 2020
     */
    int insert(Compitition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table compitition
     *
     * @mbg.generated Wed Nov 11 22:13:40 CST 2020
     */
    int insertSelective(Compitition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table compitition
     *
     * @mbg.generated Wed Nov 11 22:13:40 CST 2020
     */
    List<Compitition> selectByExample(CompititionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table compitition
     *
     * @mbg.generated Wed Nov 11 22:13:40 CST 2020
     */
    Compitition selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table compitition
     *
     * @mbg.generated Wed Nov 11 22:13:40 CST 2020
     */
    int updateByExampleSelective(@Param("record") Compitition record, @Param("example") CompititionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table compitition
     *
     * @mbg.generated Wed Nov 11 22:13:40 CST 2020
     */
    int updateByExample(@Param("record") Compitition record, @Param("example") CompititionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table compitition
     *
     * @mbg.generated Wed Nov 11 22:13:40 CST 2020
     */
    int updateByPrimaryKeySelective(Compitition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table compitition
     *
     * @mbg.generated Wed Nov 11 22:13:40 CST 2020
     */
    int updateByPrimaryKey(Compitition record);
}